{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintkCP where

-- pretty-printer generated by the BNF converter

import AbskCP
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))
  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])



instance Print Program where
  prt i e = case e of
   Progr declarations -> prPrec i 0 (concatD [prt 0 declarations])


instance Print Declaration where
  prt i e = case e of
   ProcDecl declarator compound_stm -> prPrec i 0 (concatD [doc (showString "proc") , prt 0 declarator , prt 0 compound_stm])
   VarDecl type_specifier init_declarators -> prPrec i 0 (concatD [prt 0 type_specifier , prt 0 init_declarators , doc (showString ";")])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Init_declarator where
  prt i e = case e of
   OnlyDecl id -> prPrec i 0 (concatD [prt 0 id])
   InitDecl id exp -> prPrec i 0 (concatD [prt 0 id , doc (showString "=") , prt 1 exp])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Type_specifier where
  prt i e = case e of
   Tint  -> prPrec i 0 (concatD [doc (showString "int")])
   Tbool  -> prPrec i 0 (concatD [doc (showString "bool")])


instance Print Declarator where
  prt i e = case e of
   FuncIdent id parameter_declarations -> prPrec i 0 (concatD [prt 0 id , doc (showString "(") , prt 0 parameter_declarations , doc (showString ")")])


instance Print Parameter_declarations where
  prt i e = case e of
   ParamDec parameter_declaration -> prPrec i 0 (concatD [prt 0 parameter_declaration])
   MoreParamDec parameter_declarations parameter_declaration -> prPrec i 0 (concatD [prt 0 parameter_declarations , doc (showString ",") , prt 0 parameter_declaration])


instance Print Parameter_declaration where
  prt i e = case e of
   TypeAndParam type_specifier id -> prPrec i 0 (concatD [prt 0 type_specifier , prt 0 id])


instance Print Stm where
  prt i e = case e of
   CompStm compound_stm -> prPrec i 0 (concatD [prt 0 compound_stm])
   ExprStm expression_stm -> prPrec i 0 (concatD [prt 0 expression_stm])
   SelecStm selection_stm -> prPrec i 0 (concatD [prt 0 selection_stm])
   IterStm iter_stm -> prPrec i 0 (concatD [prt 0 iter_stm])
   JumpStm jump_stm -> prPrec i 0 (concatD [prt 0 jump_stm])
   PrintStm print_stm -> prPrec i 0 (concatD [prt 0 print_stm])

  prtList es = case es of
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Compound_stm where
  prt i e = case e of
   ScompOne  -> prPrec i 0 (concatD [doc (showString "{") , doc (showString "}")])
   ScompTwo stms -> prPrec i 0 (concatD [doc (showString "{") , prt 0 stms , doc (showString "}")])
   ScompThree declarations -> prPrec i 0 (concatD [doc (showString "{") , prt 0 declarations , doc (showString "}")])
   ScompFour declarations stms -> prPrec i 0 (concatD [doc (showString "{") , prt 0 declarations , prt 0 stms , doc (showString "}")])


instance Print Expression_stm where
  prt i e = case e of
   SexprOne  -> prPrec i 0 (concatD [doc (showString ";")])
   SexprTwo exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])


instance Print Selection_stm where
  prt i e = case e of
   SselOne exp compound_stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 compound_stm])
   SselTwo exp compound_stm0 compound_stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 compound_stm0 , doc (showString "else") , prt 0 compound_stm])


instance Print Iter_stm where
  prt i e = case e of
   SiterOne exp compound_stm -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 compound_stm])
   SiterTwo compound_stm exp -> prPrec i 0 (concatD [doc (showString "do") , prt 0 compound_stm , doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , doc (showString ";")])
   SiterThree expression_stm0 expression_stm compound_stm -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 expression_stm0 , prt 0 expression_stm , doc (showString ")") , prt 0 compound_stm])
   SiterFour expression_stm0 expression_stm exp compound_stm -> prPrec i 0 (concatD [doc (showString "for") , doc (showString "(") , prt 0 expression_stm0 , prt 0 expression_stm , prt 0 exp , doc (showString ")") , prt 0 compound_stm])


instance Print Jump_stm where
  prt i e = case e of
   SjumpTwo  -> prPrec i 0 (concatD [doc (showString "continue") , doc (showString ";")])
   SjumpThree  -> prPrec i 0 (concatD [doc (showString "break") , doc (showString ";")])
   SjumpFour  -> prPrec i 0 (concatD [doc (showString "return") , doc (showString ";")])
   SjumpFive exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])


instance Print Print_stm where
  prt i e = case e of
   Sprint exps -> prPrec i 0 (concatD [doc (showString "print(") , prt 1 exps , doc (showString ")") , doc (showString ";")])


instance Print Constant where
  prt i e = case e of
   Eint n -> prPrec i 0 (concatD [prt 0 n])
   Ebool boolean -> prPrec i 0 (concatD [prt 0 boolean])


instance Print Boolean where
  prt i e = case e of
   Vtrue  -> prPrec i 0 (concatD [doc (showString "true")])
   Vfalse  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print Constant_expression where
  prt i e = case e of
   Especial exp -> prPrec i 0 (concatD [prt 3 exp])


instance Print Exp where
  prt i e = case e of
   Eassign exp0 assignment_op exp -> prPrec i 1 (concatD [prt 8 exp0 , prt 0 assignment_op , prt 1 exp])
   Elor exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "||") , prt 4 exp])
   Eland exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "&&") , prt 4 exp])
   Eeq exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "==") , prt 5 exp])
   Eneq exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "!=") , prt 5 exp])
   Elthen exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "<") , prt 6 exp])
   Egrthen exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString ">") , prt 6 exp])
   Ele exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "<=") , prt 6 exp])
   Ege exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString ">=") , prt 6 exp])
   Eplus exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "+") , prt 7 exp])
   Eminus exp0 exp -> prPrec i 6 (concatD [prt 6 exp0 , doc (showString "-") , prt 7 exp])
   Etimes exp0 exp -> prPrec i 7 (concatD [prt 7 exp0 , doc (showString "*") , prt 8 exp])
   Ediv exp0 exp -> prPrec i 7 (concatD [prt 7 exp0 , doc (showString "/") , prt 8 exp])
   Emod exp0 exp -> prPrec i 7 (concatD [prt 7 exp0 , doc (showString "%") , prt 8 exp])
   Epreinc exp -> prPrec i 8 (concatD [doc (showString "++") , prt 8 exp])
   Epredec exp -> prPrec i 8 (concatD [doc (showString "--") , prt 8 exp])
   Epreop unary_operator exp -> prPrec i 8 (concatD [prt 0 unary_operator , prt 8 exp])
   Efunk exp -> prPrec i 9 (concatD [prt 9 exp , doc (showString "(") , doc (showString ")")])
   Efunkpar exp exps -> prPrec i 9 (concatD [prt 9 exp , doc (showString "(") , prt 1 exps , doc (showString ")")])
   Epostinc exp -> prPrec i 9 (concatD [prt 9 exp , doc (showString "++")])
   Epostdec exp -> prPrec i 9 (concatD [prt 9 exp , doc (showString "--")])
   Evar id -> prPrec i 10 (concatD [prt 0 id])
   Econst constant -> prPrec i 10 (concatD [prt 0 constant])

  prtList es = case es of
   [x] -> (concatD [prt 1 x])
   x:xs -> (concatD [prt 1 x , doc (showString ",") , prt 1 xs])

instance Print Unary_operator where
  prt i e = case e of
   Plus  -> prPrec i 0 (concatD [doc (showString "+")])
   Negative  -> prPrec i 0 (concatD [doc (showString "-")])
   Logicalneg  -> prPrec i 0 (concatD [doc (showString "!")])


instance Print Assignment_op where
  prt i e = case e of
   Assign  -> prPrec i 0 (concatD [doc (showString "=")])
   AssignMul  -> prPrec i 0 (concatD [doc (showString "*=")])
   AssignDiv  -> prPrec i 0 (concatD [doc (showString "/=")])
   AssignMod  -> prPrec i 0 (concatD [doc (showString "%=")])
   AssignAdd  -> prPrec i 0 (concatD [doc (showString "+=")])
   AssignSub  -> prPrec i 0 (concatD [doc (showString "-=")])
   AssignAnd  -> prPrec i 0 (concatD [doc (showString "&=")])
   AssignOr  -> prPrec i 0 (concatD [doc (showString "|=")])



